### ISSUE TITLE
Back to CRAN?

### ISSUE THREAD

**Issue by atsyplenkov** [JosiahParry/rsgeo#48] opened 2024-09-29 03:36 UTC
Hey, what's up with {rsgeo} on CRAN? Need any help getting it back there?

**Comment by JosiahParry** [comment] 2024-09-29 04:29
The required version of Rust to use current versions of geo is 1.75 which is far newer than CRAN will likely permit.

**Comment by Robinlovelace** [comment] 2024-10-03 14:13
Update here, have got it working locally for our networkmerge project, with the following (installing the stable version fails):

```bash
# Update rust to unstable latest version:
# rustup update stable # fails
rustup update nightly # works
```

```{r}
#| name: python-setup
# Install remotes if not already:
if (!requireNamespace("remotes")) {
  install.packages("remotes")
}
remotes::install_github("josiahparry/rsgeo")
install.packages(
  'rsgeo', 
  repos = c('https://josiahparry.r-universe.dev', 'https://cloud.r-project.org')
)
```

**Comment by Robinlovelace** [comment] 2024-10-03 14:31
Out of interest, why did `geo` switch to relying on nightly not stable version of Rust? Would have saved some people (well at least me and @wangzhao0217) some time if we didn't have to go to nightly rust for this to work.

**Comment by Robinlovelace** [comment] 2024-10-03 14:38
See upstream fix here: https://github.com/geocompx/docker/issues/81

**Comment by JosiahParry** [comment] 2024-10-03 15:16
@Robinlovelace you probably needed to run `cargo clean` and not actually change to a nightly distribution. Or the tooling you were using is out of date.

I was not able to reproduce the issue. 

See 
<img width="641" alt="image" src="https://github.com/user-attachments/assets/d4a53820-7eb7-48d5-af44-920f531cff88">

and 
<img width="917" alt="image" src="https://github.com/user-attachments/assets/55349090-e70a-498c-963a-065040944f73">


The version of geo that rsgeo relies on requires a minimum version of rust that is 1.74.

They have a _very_ relaxed MSRV position since the library is still solidifying its API.

**Comment by JosiahParry** [comment] 2024-10-03 15:18
I am going to close this because I do not foresee CRAN bumping their MSRV for a while.

As of today these are their rust versions:

|flavor                            |rustc  |cargo  |
|:---------------------------------|:------|:------|
|r-devel-linux-x86_64-fedora-clang |1.69.0 |1.69.0 |
|r-devel-linux-x86_64-fedora-gcc   |1.69.0 |1.69.0 |
|r-devel-linux-x86_64-fedora-clang |1.69.0 |1.69.0 |
|r-release-macos-arm64             |1.70.0 |1.70.0 |
|r-release-macos-x86_64            |1.70.0 |1.70.0 |
|r-oldrel-macos-arm64              |1.70.0 |1.70.0 |
|r-oldrel-macos-x86_64             |1.70.0 |1.70.0 |
|r-release-macos-arm64             |1.70.0 |1.70.0 |
|r-release-macos-x86_64            |1.70.0 |1.70.0 |
|r-oldrel-macos-arm64              |1.70.0 |1.70.0 |
|r-oldrel-macos-x86_64             |1.70.0 |1.70.0 |
|r-devel-windows-x86_64            |1.76.0 |1.76.0 |
|r-release-windows-x86_64          |1.76.0 |1.76.0 |
|r-oldrel-windows-x86_64           |1.76.0 |1.76.0 |
|r-devel-linux-x86_64-debian-clang |1.80.1 |1.80.1 |
|r-devel-linux-x86_64-debian-gcc   |1.80.1 |1.80.1 |
|r-patched-linux-x86_64            |1.80.1 |1.80.1 |
|r-release-linux-x86_64            |1.80.1 |1.80.1 |


I got `{arcpbf}` published with an MSRV of `1.70` but that was not easy and required 2 weeks of review.

**Comment by Robinlovelace** [comment] 2024-10-03 15:36
Hopefully CRAN update their stuff before too long!

**Closed as completed** 2024-10-03 15:35 UTC

**Comment by JosiahParry** [comment] 2024-10-03 15:37
@Robinlovelace it might be worth being a voice at https://github.com/extendr/extendr/discussions/849 even if it is as simple as "we need rust in our R packages. not having modern tooling available in rust is a hinderance to the language as a whole"

**Comment by Robinlovelace** [comment] 2024-10-03 19:16
:+1: done
